import dayjs from "dayjs";
import utc from "dayjs/plugin/utc.js";
import timezone from "dayjs/plugin/timezone.js";
import { randomUUID } from "crypto";

dayjs.extend(utc);
dayjs.extend(timezone);

export function normalizeDateToken(value) {
  if (!value && value !== 0) return null;
  if (typeof value === "string") {
    const trimmed = value.trim();
    if (!trimmed) return null;
    const isoMatch = dayjs(trimmed);
    if (isoMatch.isValid()) return isoMatch.toISOString();
    try {
      const parsed = new Date(trimmed);
      if (!Number.isNaN(parsed.getTime())) return parsed.toISOString();
    } catch {
      return null;
    }
    return null;
  }
  if (value instanceof Date) {
    if (Number.isNaN(value.getTime())) return null;
    return value.toISOString();
  }
  if (typeof value?.toDate === "function") {
    try {
      return value.toDate().toISOString();
    } catch {
      return null;
    }
  }
  if (typeof value === "number") {
    const d = new Date(value);
    if (!Number.isNaN(d.getTime())) return d.toISOString();
  }
  return null;
}

function normalizeBool(value, fallback = false) {
  if (typeof value === "boolean") return value;
  if (typeof value === "number") return value !== 0;
  if (typeof value === "string") {
    const token = value.trim().toLowerCase();
    if (["true", "yes", "done", "1"].includes(token)) return true;
    if (["false", "no", "0", "pending"].includes(token)) return false;
  }
  return fallback;
}

function normalizeTitle(value, fallback = "Milestone") {
  if (typeof value !== "string") return fallback;
  const trimmed = value.trim();
  if (!trimmed) return fallback;
  return trimmed.length > 160 ? `${trimmed.slice(0, 157)}...` : trimmed;
}

function normalizeNote(value) {
  if (typeof value !== "string") return "";
  const trimmed = value.trim();
  return trimmed.length > 600 ? `${trimmed.slice(0, 597)}...` : trimmed;
}

function coercePriority(value) {
  if (value === null || value === undefined) return null;
  if (typeof value === "number" && Number.isFinite(value)) return Math.max(-1, Math.min(5, value));
  if (typeof value === "string" && value.trim()) {
    const num = Number(value);
    if (Number.isFinite(num)) return Math.max(-1, Math.min(5, num));
  }
  return null;
}

export function sanitizeMilestones(list = []) {
  if (!Array.isArray(list)) return [];
  return list
    .map((item, index) => {
      if (!item && item !== 0) return null;
      const milestone = typeof item === "object" ? item : { title: String(item) };
      const deadline = normalizeDateToken(milestone.deadline || milestone.date || milestone.targetDate);
      return {
        id: milestone.id || randomUUID(),
        title: normalizeTitle(milestone.title || milestone.name || `Milestone ${index + 1}`),
        description: normalizeNote(milestone.description || milestone.note || ""),
        deadline,
        completed: normalizeBool(milestone.completed, false),
        autoGenerated: Boolean(milestone.autoGenerated || milestone.source === "ai"),
        priority: coercePriority(milestone.priority),
        reminderId: milestone.reminderId || null,
        reminderScheduled: normalizeBool(milestone.reminderScheduled, false),
        reminderSyncedAt: milestone.reminderSyncedAt || null,
        timezone: milestone.timezone || null,
        channels: Array.isArray(milestone.channels) ? milestone.channels : undefined,
        taskId: milestone.taskId || null,
      };
    })
    .filter(Boolean);
}

export function computeGoalProgress(milestones = [], fallback = 0) {
  if (!Array.isArray(milestones) || !milestones.length) return Number(fallback) || 0;
  const total = milestones.length;
  const completed = milestones.filter((item) => item?.completed).length;
  return Math.max(0, Math.min(1, completed / total));
}

export function buildGoalSummary(goal) {
  if (!goal || typeof goal !== "object") return null;
  const base = {
    title: goal.title,
    category: goal.category,
    targetDate: normalizeDateToken(goal.targetDate),
    description: goal.description,
  };
  if (!base.targetDate && goal?.milestones?.length) {
    const deadlines = goal.milestones
      .map((m) => normalizeDateToken(m.deadline))
      .filter(Boolean)
      .sort();
    base.targetDate = deadlines[deadlines.length - 1] || null;
  }
  return base;
}

export function serializeGoal(goal) {
  if (!goal) return null;
  const toIso = (value) => {
    const iso = normalizeDateToken(value);
    return iso;
  };
  const data = {
    ...goal,
    createdAt: goal.createdAt?.toDate ? goal.createdAt.toDate().toISOString() : toIso(goal.createdAt) || null,
    updatedAt: goal.updatedAt?.toDate ? goal.updatedAt.toDate().toISOString() : toIso(goal.updatedAt) || null,
    targetDate: toIso(goal.targetDate) || null,
  };
  if (Array.isArray(data.milestones)) {
    data.milestones = data.milestones.map((m) => ({
      ...m,
      deadline: toIso(m.deadline) || null,
      reminderSyncedAt: toIso(m.reminderSyncedAt) || null,
    }));
  }
  return data;
}
