import OpenAI from "openai";
import { randomUUID } from "crypto";
import { sanitizeMilestones } from "../utils/progress.js";

let openaiClient = null;

function getClient() {
  if (!process.env.OPENAI_API_KEY) return null;
  if (!openaiClient) {
    openaiClient = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  }
  return openaiClient;
}

function fallbackMilestones(goalInput = {}) {
  const title = goalInput.title || "Your goal";
  return sanitizeMilestones([
    { title: `${title}: Define success`, description: "Clarify why this matters and set metrics." },
    { title: `${title}: Build momentum`, description: "Create weekly rituals that move the goal forward." },
    { title: `${title}: Execute key milestone`, description: "Deliver the most impactful sub-goal." },
    { title: `${title}: Review & adjust`, description: "Reflect on progress and refine next steps." },
  ]).map((item) => ({ ...item, autoGenerated: true }));
}

export async function generateMilestonesWithAI(goalInput = {}, options = {}) {
  const client = getClient();
  if (!client) return fallbackMilestones(goalInput);

  const model = options.model || process.env.GOALS_OPENAI_MODEL || "gpt-4o-mini";
  const instructions = `You are an AI goal architect. Convert the goal below into 3-6 SMART milestones.
Return strict JSON with the shape:
[
  {"title":"string","description":"string","deadline":"YYYY-MM-DD"}
]
Avoid prose, no markdown.`;

  const detail = JSON.stringify({
    title: goalInput.title,
    description: goalInput.description,
    category: goalInput.category,
    targetDate: goalInput.targetDate,
    timeframe: options.timeframe || goalInput.timeframe || null,
  });

  try {
    const response = await client.chat.completions.create({
      model,
      temperature: 0.2,
      messages: [
        { role: "system", content: instructions },
        { role: "user", content: detail },
      ],
    });
    const raw = response.choices?.[0]?.message?.content?.trim();
    if (!raw) return fallbackMilestones(goalInput);

    let parsed = null;
    try {
      let jsonText = raw;
      const fenced = raw.match(/```json([\\s\\S]*?)```/i) || raw.match(/```([\\s\\S]*?)```/i);
      if (fenced && fenced[1]) {
        jsonText = fenced[1].trim();
      }
      parsed = JSON.parse(jsonText);
      if (!Array.isArray(parsed)) {
        parsed = parsed.milestones || parsed.data || parsed.items || [];
      }
    } catch (err) {
      console.warn("[GoalsService] Unable to parse AI milestone JSON", err?.message || err);
      parsed = [];
    }

    const sanitized = sanitizeMilestones(Array.isArray(parsed) ? parsed : []);
    if (!sanitized.length) return fallbackMilestones(goalInput);

    return sanitized.map((item) => ({ ...item, autoGenerated: true }));
  } catch (err) {
    console.error("[GoalsService] OpenAI milestone generation failed", err?.message || err);
    return fallbackMilestones(goalInput);
  }
}

export async function suggestMilestones(goalPayload = {}, options = {}) {
  const milestones = await generateMilestonesWithAI(goalPayload, options);
  return milestones.map((m) => ({ ...m, suggestionId: randomUUID() }));
}
