import fetch from "node-fetch";
import { db, FieldValue } from "./firebaseAdmin.js";

const TASK_ENDPOINT = process.env.GOALS_TASK_SERVICE_URL || process.env.TASK_SERVICE_URL || "";
const tasksCollection = () => db.collection("tasks");

function normalizeIds(list = []) {
  if (!Array.isArray(list)) return [];
  return Array.from(
    new Set(
      list
        .map((entry) => (typeof entry === "string" ? entry.trim() : String(entry || "")))
        .filter((token) => token && token !== "undefined" && token !== "null"),
    ),
  );
}

async function updateTaskGoalRef(taskId, payload) {
  if (!taskId) return null;
  try {
    await tasksCollection().doc(taskId).update(payload);
    return true;
  } catch (err) {
    console.warn(`[GoalsService] Failed to update task ${taskId}`, err?.message || err);
    return false;
  }
}

export async function syncLinkedTasks({ userId, goalId, nextLinked = [], previousLinked = [], goalSummary = {} }) {
  if (!goalId || !userId) return { attached: 0, detached: 0 };
  const nextIds = normalizeIds(nextLinked);
  const prevIds = normalizeIds(previousLinked);
  if (!nextIds.length && !prevIds.length) return { attached: 0, detached: 0 };

  const toAttach = nextIds.filter((id) => !prevIds.includes(id));
  const toDetach = prevIds.filter((id) => !nextIds.includes(id));

  const metaPayload = goalSummary?.title
    ? {
        goalTitle: goalSummary.title,
        goalTargetDate: goalSummary.targetDate || null,
        goalCategory: goalSummary.category || null,
      }
    : {};

  let attached = 0;
  let detached = 0;

  for (const taskId of toAttach) {
    const success = await updateTaskGoalRef(taskId, {
      goalId,
      ...metaPayload,
      updatedAt: FieldValue.serverTimestamp ? FieldValue.serverTimestamp() : new Date(),
    });
    if (success) attached += 1;
  }

  const deleteFieldValue = FieldValue?.delete ? FieldValue.delete() : null;

  for (const taskId of toDetach) {
    const payload = {
      updatedAt: FieldValue.serverTimestamp ? FieldValue.serverTimestamp() : new Date(),
    };
    payload.goalId = deleteFieldValue;
    payload.goalTitle = deleteFieldValue;
    payload.goalTargetDate = deleteFieldValue;
    payload.goalCategory = deleteFieldValue;
    const success = await updateTaskGoalRef(taskId, payload);
    if (success) detached += 1;
  }

  return { attached, detached };
}

export async function createTasksForMilestones({ userId, goalId, milestones = [], timezone }) {
  if (!TASK_ENDPOINT || !userId || !Array.isArray(milestones) || !milestones.length) {
    return [];
  }
  const results = [];
  for (const milestone of milestones) {
    try {
      const payload = {
        userId,
        title: milestone.title,
        details: milestone.description,
        date: milestone.deadline ? milestone.deadline.slice(0, 10) : null,
        source: "goal-milestone",
        goalId,
        metadata: { milestoneId: milestone.id, autoGenerated: milestone.autoGenerated === true },
        timezone,
      };
      const response = await fetch(TASK_ENDPOINT, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (!response.ok) {
        const text = await response.text();
        console.warn(`[GoalsService] Task creation failed (${response.status}): ${text}`);
        results.push({ milestoneId: milestone.id, status: "error", code: response.status });
        continue;
      }
      const data = await response.json().catch(() => ({}));
      results.push({ milestoneId: milestone.id, status: "created", task: data?.task || data });
    } catch (err) {
      console.error("[GoalsService] Task creation error", err?.message || err);
      results.push({ milestoneId: milestone.id, status: "error", message: err?.message || "" });
    }
  }
  return results;
}
