export const PROJECT_EVENTS = {
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  SPRINT_CREATED: "SPRINT_CREATED",
  SPRINT_STARTED: "SPRINT_STARTED",
  SPRINT_COMPLETED: "SPRINT_COMPLETED",
  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  FEEDBACK_INGESTED: "FEEDBACK_INGESTED",
};
